"""ngo_module_tables

Revision ID: 8017926abc6d
Revises: f7a8b9c0d1e2
Create Date: 2026-03-06 17:20:06.658608

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8017926abc6d"
down_revision: Union[str, None] = "f7a8b9c0d1e2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ngo_notifications",
        sa.Column("ngo_id", sa.String(length=36), nullable=False),
        sa.Column(
            "event_type",
            sa.Enum(
                "DONATION_REQUEST_APPROVED",
                "DONATION_REQUEST_REJECTED",
                "PICKUP_SCHEDULED",
                "PICKUP_COMPLETED",
                "NEW_NEARBY_DONATION",
                name="ngo_notification_type",
            ),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("reference_id", sa.String(length=36), nullable=True),
        sa.Column("is_read", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["ngo_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ngo_notifications_event_type"), "ngo_notifications", ["event_type"], unique=False
    )
    op.create_index(
        op.f("ix_ngo_notifications_is_read"), "ngo_notifications", ["is_read"], unique=False
    )
    op.create_index(
        op.f("ix_ngo_notifications_ngo_id"), "ngo_notifications", ["ngo_id"], unique=False
    )
    op.create_table(
        "ngo_service_areas",
        sa.Column("ngo_id", sa.String(length=36), nullable=False),
        sa.Column("city", sa.String(length=100), nullable=True),
        sa.Column("pincode", sa.String(length=20), nullable=True),
        sa.Column("latitude", sa.Numeric(precision=10, scale=7), nullable=True),
        sa.Column("longitude", sa.Numeric(precision=10, scale=7), nullable=True),
        sa.Column("coverage_radius_km", sa.Numeric(precision=8, scale=2), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["ngo_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ngo_service_areas_ngo_id"), "ngo_service_areas", ["ngo_id"], unique=False
    )
    op.create_table(
        "ngo_distribution_records",
        sa.Column("ngo_id", sa.String(length=36), nullable=False),
        sa.Column("donation_request_id", sa.String(length=36), nullable=True),
        sa.Column("food_quantity_received", sa.Numeric(precision=10, scale=3), nullable=False),
        sa.Column("beneficiaries_served", sa.Integer(), nullable=False),
        sa.Column("distribution_location", sa.String(length=500), nullable=True),
        sa.Column("distribution_date", sa.Date(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["donation_request_id"], ["ngo_listing_requests.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["ngo_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ngo_distribution_records_donation_request_id"),
        "ngo_distribution_records",
        ["donation_request_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ngo_distribution_records_ngo_id"),
        "ngo_distribution_records",
        ["ngo_id"],
        unique=False,
    )
    op.create_table(
        "ngo_environmental_impact",
        sa.Column("ngo_id", sa.String(length=36), nullable=False),
        sa.Column("donation_request_id", sa.String(length=36), nullable=False),
        sa.Column("food_saved_kg", sa.Numeric(precision=10, scale=3), nullable=False),
        sa.Column("co2_reduction_kg", sa.Numeric(precision=10, scale=3), nullable=False),
        sa.Column("landfill_waste_reduction_kg", sa.Numeric(precision=10, scale=3), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["donation_request_id"], ["ngo_listing_requests.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["ngo_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ngo_environmental_impact_donation_request_id"),
        "ngo_environmental_impact",
        ["donation_request_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_ngo_environmental_impact_ngo_id"),
        "ngo_environmental_impact",
        ["ngo_id"],
        unique=False,
    )
    op.add_column(
        "ngo_profiles", sa.Column("lat", sa.Numeric(precision=10, scale=7), nullable=True)
    )
    op.add_column(
        "ngo_profiles", sa.Column("lng", sa.Numeric(precision=10, scale=7), nullable=True)
    )
    op.add_column(
        "ngo_profiles",
        sa.Column("operating_radius_km", sa.Numeric(precision=8, scale=2), nullable=True),
    )
    op.add_column(
        "ngo_profiles",
        sa.Column(
            "ngo_type",
            sa.Enum(
                "FOOD_BANK",
                "SHELTER",
                "COMMUNITY_KITCHEN",
                "ORPHANAGE",
                "OLD_AGE_HOME",
                "OTHER",
                name="ngo_type",
            ),
            nullable=True,
        ),
    )
    op.add_column(
        "ngo_profiles",
        sa.Column(
            "verification_status",
            sa.Enum("PENDING", "VERIFIED", "REJECTED", name="ngo_verification_status"),
            nullable=False,
        ),
    )
    op.add_column("ngo_profiles", sa.Column("document_url", sa.Text(), nullable=True))
    op.add_column(
        "ngo_profiles", sa.Column("contact_person_name", sa.String(length=200), nullable=True)
    )
    op.add_column("ngo_profiles", sa.Column("vehicle_type", sa.String(length=100), nullable=True))
    op.add_column("ngo_profiles", sa.Column("open_time", sa.String(length=8), nullable=True))
    op.add_column("ngo_profiles", sa.Column("close_time", sa.String(length=8), nullable=True))
    op.add_column("ngo_profiles", sa.Column("closed_days", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("ngo_profiles", "closed_days")
    op.drop_column("ngo_profiles", "close_time")
    op.drop_column("ngo_profiles", "open_time")
    op.drop_column("ngo_profiles", "vehicle_type")
    op.drop_column("ngo_profiles", "contact_person_name")
    op.drop_column("ngo_profiles", "document_url")
    op.drop_column("ngo_profiles", "verification_status")
    op.drop_column("ngo_profiles", "ngo_type")
    op.drop_column("ngo_profiles", "operating_radius_km")
    op.drop_column("ngo_profiles", "lng")
    op.drop_column("ngo_profiles", "lat")
    op.drop_index(op.f("ix_ngo_environmental_impact_ngo_id"), table_name="ngo_environmental_impact")
    op.drop_index(
        op.f("ix_ngo_environmental_impact_donation_request_id"),
        table_name="ngo_environmental_impact",
    )
    op.drop_table("ngo_environmental_impact")
    op.drop_index(op.f("ix_ngo_distribution_records_ngo_id"), table_name="ngo_distribution_records")
    op.drop_index(
        op.f("ix_ngo_distribution_records_donation_request_id"),
        table_name="ngo_distribution_records",
    )
    op.drop_table("ngo_distribution_records")
    op.drop_index(op.f("ix_ngo_service_areas_ngo_id"), table_name="ngo_service_areas")
    op.drop_table("ngo_service_areas")
    op.drop_index(op.f("ix_ngo_notifications_ngo_id"), table_name="ngo_notifications")
    op.drop_index(op.f("ix_ngo_notifications_is_read"), table_name="ngo_notifications")
    op.drop_index(op.f("ix_ngo_notifications_event_type"), table_name="ngo_notifications")
    op.drop_table("ngo_notifications")
    # ### end Alembic commands ###
