"""Import all models so SQLAlchemy / Alembic can discover them."""

from app.models.base import Base  # noqa: F401
from app.models.user import User, UserRole  # noqa: F401
from app.models.profiles import (  # noqa: F401
    ConsumerProfile,
    SellerProfile,
    NGOProfile,
    InspectorProfile,
    ProfileCompletionStatus,
    SellerVerificationStatus,
)
from app.models.food import (  # noqa: F401
    FoodListing,
    Order,
    OrderItem,
    Favorite,
    ImpactStat,
    SellerReview,
    SellerNotification,
    InventoryTracking,
    NGOListingRequest,
    PickupRecord,
    EnvironmentalImpactRecord,
    InspectorJurisdiction,
    SellerVerification,
    NGOVerification,
    FoodInspection,
    ViolationRecord,
    ComplaintRecord,
    InspectionSchedule,
    ListingModeration,
    InspectorNotification,
    OrderStatus,
    FavoriteType,
    ImpactLevel,
    SellerListingStatus,
    SellerNotificationType,
    FoodType,
    PaymentStatus,
    DonationApprovalStatus,
    PickupStatus,
    VerificationMethod,
    VerificationStatus,
    InspectionType,
    InspectionStatus,
    ViolationType,
    ViolationSeverity,
    EnforcementAction,
    ComplaintType,
    ComplaintStatus,
    InspectionScheduleType,
    InspectionScheduleStatus,
    ModerationStatus,
    InspectorNotificationType,
)
from app.models.ngo import (  # noqa: F401
    NGODistributionRecord,
    NGOEnvironmentalImpact,
    NGONotification,
    NGOServiceArea,
    NGONotificationType,
)
